In [2]:
import numpy as np


In [6]:
a=np.array([1,2,3])

In [8]:
b=np.array([4,5,6])

In [12]:
a+b


array([5, 7, 9])

In [14]:
c=np.arange(1,99)

In [16]:
c


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [18]:
a=np.ones((3,2),dtype=np.int64)

In [19]:
a


array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int64)

In [23]:
x=np.arange(9).reshape((3,3))


In [24]:
np.diag(x)

array([0, 4, 8])

In [25]:
x=np.diag([1,2,3])

In [30]:
x=np.diag(np.ones((3),dtype=np.int64))


In [33]:
x


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int64)